name: hexlet-ci-app
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install Strapi
        run: npm install @strapi/design-system
      - name: Setup app
        run: make setup
      - name: Testing
        run: make test
      - name: Linting
        run: make lint
